name             'cookbook_versions'
maintainer       'Irving Popovetsky'
maintainer_email 'irving@chef.io'
license          'all_rights'
description      'Installs/Configures cookbook_versions'
long_description 'Installs/Configures cookbook_versions'
version          '0.4.0'
source_url       'https://github.com/irvingpop/cookbook_versions'
issues_url       'https://github.com/irvingpop/cookbook_versions/issues'
